baseURL = 'https://mali181.github.io/mali181/'
languageCode = 'en-us'
title = '我的新闻集'
theme = 'ananke'
publishDir = "docs"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true